Fix TS errors in codebase
Fixes the following Typescript errors:
- Property 'refetch' does not exist on type '{ bookingsWithTasks: BookingWithTask[]; loading: boolean; error: string; }'.
- Property 'message' does not exist on type 'string'.
- Cannot find name 'Button'.
- Type '{ address: Json; created_at: string; first_synced_at: string; highres_url: string; id: string; is_deleted: boolean; last_synced: string; property_type: string; raw_data: Json; status: string; sync_status: string; thumbnail_url: string; title: string; updated_at: string; }[]' is not assignable to type 'GuestyListingDB[]'.